# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="lektor-algolia",
    version="0.1.0",
    description="Lektor plugin to support generating an Algolia search index from your data",
    python_requires="==3.*,>=3.7.0",
    project_urls={"homepage": "https://github.com/sherbondy/lektor-algolia"},
    author="Ethan Sherbondy",
    author_email="sherbondye@gmail.com",
    license="MIT",
    packages=[],
    package_dir={"": "src"},
    package_data={},
    install_requires=["algoliasearch", "devtools", "lektor"],
    entry_points={
        'lektor.plugins': [
            'algolia = lektor_algolia:AlgoliaPlugin',
        ]
    }
)
